# -*- coding: utf-8 -*-
"""Taylor-Clark-Assignment1-Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cZYWvXXAr0gjKXYzlHJxMikhmGGil07z

<h1>Loading the Dataset</h1>
"""

import pandas as pd

!pip install xlrd

df = pd.read_excel("KEL444-XLS-ENG.xls", sheet_name="DoubleClick Data")

df.head()

"""<h1>Question 1</h1>"""

# Summarize the data by publisher
publisher_summary = df.groupby('Publisher Name').agg({
    'Trans. Conv. %': 'mean',
    'Net Revenue': 'sum',
    'Return on Ad Dollar Spent': 'mean'
}).reset_index()

# Normalize metrics for fair comparison, scaling each metric between 0 and 1
normalized = publisher_summary.copy()
normalized[['Trans. Conv. %', 'Net Revenue', 'Return on Ad Dollar Spent']] = (
    publisher_summary[['Trans. Conv. %', 'Net Revenue', 'Return on Ad Dollar Spent']]
    .apply(lambda x: (x - x.min()) / (x.max() - x.min()))
)

# Plot grouped bar chart
chart = normalized.set_index('Publisher Name').plot(
    kind='bar',
    figsize=(12,6),
    width=0.75,
    color=['#4E79A7', '#F28E2B', '#76B7B2']
)

"""<h1>Question 2</h1>"""

publisher_summary = df.groupby('Publisher Name').agg({
    'Trans. Conv. %': 'mean',
    'Net Revenue': 'sum',
    'Return on Ad Dollar Spent': 'mean'
}).reset_index()

publisher_summary.sort_values(by='Net Revenue', ascending=False)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,7))

# Bubble chart
sns.scatterplot(
    data=publisher_summary,
    x='Return on Ad Dollar Spent',
    y='Trans. Conv. %',
    size='Net Revenue',
    hue='Publisher Name',
    sizes=(100, 2000),   # Adjust bubble size scale
    alpha=0.7
)

plt.title('Publisher Performance: Conversion vs ROAS (Bubble Size = Net Revenue)')
plt.xlabel('Return on Ad Dollar Spent')
plt.ylabel('Transaction Conversion %')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True)
plt.show()

"""<h1>Question 3</h1>"""

# Summarize average rates by publisher
publisher_rates = df.groupby('Publisher Name').agg({
    'Trans. Conv. %': 'mean',
    'Engine Click Thru %': 'mean'
}).reset_index()

# Melt data for easy grouped plotting
rates_melted = publisher_rates.melt(id_vars='Publisher Name',
                                    value_vars=['Trans. Conv. %', 'Engine Click Thru %'],
                                    var_name='Metric',
                                    value_name='Percentage')

# Plot the data
plt.figure(figsize=(10,6))
sns.barplot(data=rates_melted, x='Publisher Name', y='Percentage', hue='Metric')

"""<h1>Question 4</h1>"""

google_us = df[df['Publisher Name'] == 'Google - US']

google_us['Campaign'].nunique(), google_us.shape

campaign_performance = (
    google_us.groupby('Campaign', as_index=False)['Net Revenue']
    .sum()
    .sort_values('Net Revenue', ascending=False)
)

top5 = campaign_performance.head(5)
bottom5 = campaign_performance.tail(5)

print("Top 5 Google - US Campaigns by Net Revenue:")
print(top5)

print("\nBottom 5 Google - US Campaigns by Net Revenue:")
print(bottom5)

"""<h1>Question 5</h1>"""

msn_us = df[df['Publisher Name'] == 'MSN - US']

msn_us[['Keyword', 'Match Type', 'Return on Ad Dollar Spent']].head()

keyword_roas = (
    msn_us.groupby(['Keyword', 'Match Type'], as_index=False)['Return on Ad Dollar Spent']
    .mean()
    .sort_values('Return on Ad Dollar Spent', ascending=False)
)

keyword_roas.head(10)

plt.figure(figsize=(10,6))
sns.boxplot(data=msn_us, x='Match Type', y='Return on Ad Dollar Spent')
plt.title('Distribution of ROAS by Match Type (MSN U.S.)')
plt.show()

top_keywords = keyword_roas.head(10)
plt.figure(figsize=(10,6))
sns.barplot(data=top_keywords, x='Return on Ad Dollar Spent', y='Keyword', hue='Match Type', dodge=False, palette='viridis')
plt.title('Top 10 Keywords by ROAS (MSN U.S.)')
plt.xlabel('Average Return on Ad Dollar Spent')
plt.ylabel('Keyword')
plt.show()

"""<h1>Question 6</h1>"""

# Select relevant columns
cols = ['Engine Click Thru %', 'Click Charges', 'Avg. Cost per Click',
        'Probability of Booking', 'Avg. Pos.']

# Get the correlation
corr = df[cols].corr()

# Plot correlation heatmap
plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Between Metrics and Average Position', fontsize=14, fontweight='bold')
plt.show()

# Select numeric columns
numeric_df = df.select_dtypes(include='number')

# Compute correlations with Avg. Pos.
corr_with_avgpos = numeric_df.corr()['Avg. Pos.'].sort_values(ascending=False)

# Display as a horizontal bar chart
plt.figure(figsize=(8,6))
corr_with_avgpos.drop('Avg. Pos.').plot(kind='barh', color='steelblue')
plt.title('Correlation of Metrics with Average Position', fontsize=14, fontweight='bold')
plt.xlabel('Correlation Coefficient')
plt.ylabel('Metric')
plt.grid(axis='x', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()